name: Test

on:
  workflow_dispatch:
  push:
    branches: '**'

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest           
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: 5.9

      - name: Get swift version
        run: swift --version 

      - name: Test
        run: swift test
